"""
Prepare the fixed subset used for finite-shot and hardware experiments.

The script selects 10 training samples per class and 10 test samples per
subclass (SEP, PPT and NPPT) using the fixed seed defined in ``config.py``.
It reuses the PCA-transformed data and ideal kernel matrices generated by
``01_reference_statevector.py``, so no PCA fitting or kernel computation
is repeated.

Outputs are written to ``results_tfm/``:
    - subset_indices.json
    - subset_train.csv
    - subset_test.csv
    - subset_ideal_K_train.csv
    - subset_ideal_K_test.csv
    - subset_ideal_metrics.json
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from sklearn.svm import SVC

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tfm_experiment import common, config


SUBTYPES = ("SEP", "PPT", "NPPT")

REQUIRED_INPUTS = (
    "reference_pca_train.csv",
    "reference_pca_test.csv",
    "reference_K_train.csv",
    "reference_K_test.csv",
)


def _require_reference_outputs() -> None:
    missing = [
        name
        for name in REQUIRED_INPUTS
        if not (config.RESULTS_DIR / name).exists()
    ]
    if missing:
        raise FileNotFoundError(
            "Missing outputs from step 01: "
            + ", ".join(missing)
            + ". Run tfm_experiment/01_reference_statevector.py first."
        )


def _select_from_pool(pool: np.ndarray, size: int, rng: np.random.Generator) -> np.ndarray:
    if size > len(pool):
        raise ValueError(f"Requested {size} samples from a pool of {len(pool)}.")
    return np.sort(rng.choice(pool, size=size, replace=False))


def build_subset_indices(
    y_train: np.ndarray,
    y_test: np.ndarray,
    seed: int,
    n_train_per_class: int,
    n_test_per_subclass: int,
) -> tuple[np.ndarray, np.ndarray, list[str]]:
    """
    Return training/test indices and the SEP/PPT/NPPT tag of each test sample.
    The test dataset follows the original ordering:
    SEP first, followed by PPT-entangled and NPPT-entangled samples.
    """
    rng = np.random.default_rng(seed)

    sep_train_pool = np.flatnonzero(y_train == config.LABEL_SEP)
    ent_train_pool = np.flatnonzero(y_train == config.LABEL_ENTANGLED)
    train_idx = np.concatenate(
        [
            _select_from_pool(sep_train_pool, n_train_per_class, rng),
            _select_from_pool(ent_train_pool, n_train_per_class, rng),
        ]
    )

    block = config.TEST_SIZE // 3
    sep_pool = np.arange(0, block)
    ppt_pool = np.arange(block, 2 * block)
    nppt_pool = np.arange(2 * block, 3 * block)

    test_idx = np.concatenate(
        [
            _select_from_pool(sep_pool, n_test_per_subclass, rng),
            _select_from_pool(ppt_pool, n_test_per_subclass, rng),
            _select_from_pool(nppt_pool, n_test_per_subclass, rng),
        ]
    )
    test_subtypes = (
        [SUBTYPES[0]] * n_test_per_subclass
        + [SUBTYPES[1]] * n_test_per_subclass
        + [SUBTYPES[2]] * n_test_per_subclass
    )
    return train_idx, test_idx, test_subtypes


def main() -> None:
    common.ensure_dir(config.RESULTS_DIR)
    _require_reference_outputs()

    print("=" * 60)
    print("Preparing reproducible hardware subset")
    print(
        f"seed={config.SUBSET_SEED}, "
        f"train_per_class={config.SUBSET_TRAIN_PER_CLASS}, "
        f"test_per_subclass={config.SUBSET_TEST_PER_SUBCLASS}"
    )
    print("=" * 60)

    print("Loading PCA-transformed data from step 01 outputs.")
    x_train_pca, y_train = common.load_reference_pca_table(
        config.RESULTS_DIR / "reference_pca_train.csv"
    )
    x_test_pca, y_test = common.load_reference_pca_table(
        config.RESULTS_DIR / "reference_pca_test.csv"
    )
    if x_train_pca.shape != (config.TRAIN_SIZE, config.PCA_COMPONENTS):
        raise ValueError(
            f"Unexpected reference PCA train shape {x_train_pca.shape}."
        )
    if x_test_pca.shape != (config.TEST_SIZE, config.PCA_COMPONENTS):
        raise ValueError(
            f"Unexpected reference PCA test shape {x_test_pca.shape}."
        )

    train_idx, test_idx, test_subtypes = build_subset_indices(
        y_train,
        y_test,
        seed=config.SUBSET_SEED,
        n_train_per_class=config.SUBSET_TRAIN_PER_CLASS,
        n_test_per_subclass=config.SUBSET_TEST_PER_SUBCLASS,
    )
    print(f"Selected {len(train_idx)} training and {len(test_idx)} test samples.")

    Xtr = x_train_pca[train_idx]
    Xte = x_test_pca[test_idx]
    ytr = y_train[train_idx]
    yte = y_test[test_idx]

    train_columns = {f"pc_{i + 1}": Xtr[:, i] for i in range(config.PCA_COMPONENTS)}
    train_columns["label"] = ytr
    train_columns["train_index"] = train_idx
    common.save_labelled_table(
        config.RESULTS_DIR / "subset_train.csv", train_columns
    )

    test_columns = {f"pc_{i + 1}": Xte[:, i] for i in range(config.PCA_COMPONENTS)}
    test_columns["label"] = yte
    test_columns["subtype"] = np.array(test_subtypes)
    test_columns["test_index"] = test_idx
    common.save_labelled_table(
        config.RESULTS_DIR / "subset_test.csv", test_columns
    )

    common.save_json(
        {
            "seed": int(config.SUBSET_SEED),
            "train_per_class": int(config.SUBSET_TRAIN_PER_CLASS),
            "test_per_subclass": int(config.SUBSET_TEST_PER_SUBCLASS),
            "train_indices": [int(i) for i in train_idx],
            "test_indices": [int(i) for i in test_idx],
            "test_subtypes": list(test_subtypes),
        },
        config.RESULTS_DIR / "subset_indices.json",
    )

    print("Reusing reference kernel matrices from step 01 for the subset.")
    K_train_full = common.load_matrix_csv(config.RESULTS_DIR / "reference_K_train.csv")
    K_test_full = common.load_matrix_csv(config.RESULTS_DIR / "reference_K_test.csv")
    if K_train_full.shape != (config.TRAIN_SIZE, config.TRAIN_SIZE):
        raise ValueError(
            f"Unexpected reference K_train shape {K_train_full.shape}."
        )
    if K_test_full.shape != (config.TEST_SIZE, config.TRAIN_SIZE):
        raise ValueError(
            f"Unexpected reference K_test shape {K_test_full.shape}."
        )
    Ktr = K_train_full[np.ix_(train_idx, train_idx)]
    Kte = K_test_full[np.ix_(test_idx, train_idx)]

    common.save_matrix_csv(Ktr, config.RESULTS_DIR / "subset_ideal_K_train.csv")
    common.save_matrix_csv(Kte, config.RESULTS_DIR / "subset_ideal_K_test.csv")

    clf = SVC(kernel="precomputed")
    clf.fit(Ktr, ytr)
    pred_train = clf.predict(Ktr)
    pred_test = clf.predict(Kte)

    metrics = common.compute_classification_metrics(
        ytr,
        pred_train,
        yte,
        pred_test,
        block_size=config.SUBSET_TEST_PER_SUBCLASS,
    )
    metrics.update(
        {
            "seed": int(config.SUBSET_SEED),
            "train_per_class": int(config.SUBSET_TRAIN_PER_CLASS),
            "test_per_subclass": int(config.SUBSET_TEST_PER_SUBCLASS),
            "min_eigenvalue_K_train": common.min_eigenvalue(Ktr),
        }
    )
    common.save_json(metrics, config.RESULTS_DIR / "subset_ideal_metrics.json")

    print("\nSubset ideal metrics:")
    for key, value in metrics.items():
        if isinstance(value, float):
            print(f"  {key}: {value:.10f}")
        else:
            print(f"  {key}: {value}")
    print("\nSaved everything to", config.RESULTS_DIR)


if __name__ == "__main__":
    main()
